defmodule Weather.TestAPI do
  use HTTPoison.Base

  @endpoint "https://api.darksky.net"

  def process_url(url) do
    @endpoint <> url
  end

  def process_response_body(body) do
    body
    |> Jason.decode!()
  end

  def get(_url) do
    # We return this instead of actually hitting the API in tests
    {:ok,
     %HTTPoison.Response{
       body: %{
         "currently" => %{
           "apparentTemperature" => 33.17,
           "cloudCover" => 0.39,
           "dewPoint" => 21.08,
           "humidity" => 0.57,
           "icon" => "partly-cloudy-day",
           "ozone" => 258.8,
           "precipIntensity" => 0,
           "precipProbability" => 0,
           "pressure" => 1007.16,
           "summary" => "Partly Cloudy",
           "temperature" => 30.47,
           "time" => 1_569_855_466,
           "uvIndex" => 3,
           "visibility" => 16.093,
           "windBearing" => 135,
           "windGust" => 3.82,
           "windSpeed" => 2.86
         },
         "daily" => %{
           "data" => [
             %{
               "windGustTime" => 1_569_880_800,
               "pressure" => 1010.52,
               "apparentTemperatureLowTime" => 1_569_906_000,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_569_844_800,
               "ozone" => 263.2,
               "dewPoint" => 21.31,
               "temperatureLowTime" => 1_569_906_000,
               "precipIntensityMax" => 0.221,
               "apparentTemperatureMaxTime" => 1_569_844_800,
               "apparentTemperatureMax" => 33.89,
               "apparentTemperatureHigh" => 33.89,
               "apparentTemperatureMin" => 21.85,
               "icon" => "rain",
               "temperatureLow" => 22.74,
               "uvIndexTime" => 1_569_848_400,
               "precipIntensity" => 0.0363,
               "visibility" => 16.093,
               "temperatureMin" => 21.23,
               "apparentTemperatureMinTime" => 1_569_816_000,
               "temperatureMinTime" => 1_569_816_000,
               "temperatureHighTime" => 1_569_844_800,
               "precipProbability" => 0.39,
               "temperatureHigh" => 30.78,
               "time" => 1_569_798_000,
               "windGust" => 8.4,
               "windSpeed" => 2.74,
               "apparentTemperatureHighTime" => 1_569_844_800,
               "cloudCover" => 0.71,
               "windBearing" => 179,
               "temperatureMax" => 30.78,
               "sunriseTime" => 1_569_819_963,
               "precipIntensityMaxTime" => 1_569_801_600,
               "moonPhase" => 0.08,
               "sunsetTime" => 1_569_863_311,
               "summary" => "Humid and mostly cloudy throughout the day.",
               "uvIndex" => 6,
               "apparentTemperatureLow" => 23.54,
               "humidity" => 0.77
             },
             %{
               "windGustTime" => 1_569_909_600,
               "pressure" => 1009.98,
               "apparentTemperatureLowTime" => 1_569_978_000,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_569_938_400,
               "ozone" => 263.5,
               "dewPoint" => 22.31,
               "temperatureLowTime" => 1_569_981_600,
               "precipIntensityMax" => 0.468,
               "apparentTemperatureMaxTime" => 1_569_938_400,
               "apparentTemperatureMax" => 36.54,
               "apparentTemperatureHigh" => 36.54,
               "apparentTemperatureMin" => 23.54,
               "icon" => "rain",
               "temperatureLow" => 23.27,
               "uvIndexTime" => 1_569_927_600,
               "precipIntensity" => 0.0515,
               "visibility" => 15.82,
               "temperatureMin" => 22.74,
               "apparentTemperatureMinTime" => 1_569_906_000,
               "temperatureMinTime" => 1_569_906_000,
               "temperatureHighTime" => 1_569_938_400,
               "precipProbability" => 0.43,
               "temperatureHigh" => 32.11,
               "time" => 1_569_884_400,
               "windGust" => 9.01,
               "windSpeed" => 3.4,
               "apparentTemperatureHighTime" => 1_569_938_400,
               "cloudCover" => 0.72,
               "windBearing" => 218,
               "temperatureMax" => 32.11,
               "sunriseTime" => 1_569_906_360,
               "precipIntensityMaxTime" => 1_569_970_800,
               "moonPhase" => 0.12,
               "sunsetTime" => 1_569_949_673,
               "summary" => "Possible light rain in the morning and overnight.",
               "uvIndex" => 7,
               "apparentTemperatureLow" => 24.04,
               "humidity" => 0.77
             },
             %{
               "windGustTime" => 1_569_996_000,
               "pressure" => 1010.12,
               "apparentTemperatureLowTime" => 1_570_078_800,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_570_024_800,
               "ozone" => 266.8,
               "dewPoint" => 22.62,
               "temperatureLowTime" => 1_570_078_800,
               "precipIntensityMax" => 0.961,
               "apparentTemperatureMaxTime" => 1_570_024_800,
               "apparentTemperatureMax" => 35.94,
               "apparentTemperatureHigh" => 35.94,
               "apparentTemperatureMin" => 24.04,
               "icon" => "rain",
               "temperatureLow" => 21.45,
               "uvIndexTime" => 1_570_014_000,
               "precipIntensity" => 0.1872,
               "visibility" => 15.103,
               "temperatureMin" => 23.27,
               "apparentTemperatureMinTime" => 1_569_978_000,
               "temperatureMinTime" => 1_569_981_600,
               "temperatureHighTime" => 1_570_024_800,
               "precipProbability" => 0.74,
               "temperatureHigh" => 31.48,
               "time" => 1_569_970_800,
               "windGust" => 12.51,
               "windSpeed" => 3.81,
               "apparentTemperatureHighTime" => 1_570_024_800,
               "cloudCover" => 0.93,
               "windBearing" => 212,
               "temperatureMax" => 31.48,
               "sunriseTime" => 1_569_992_758,
               "precipIntensityMaxTime" => 1_569_978_000,
               "moonPhase" => 0.15,
               "sunsetTime" => 1_570_036_034,
               "summary" => "Possible light rain in the morning.",
               "uvIndex" => 5,
               "apparentTemperatureLow" => 22.25,
               "humidity" => 0.81
             },
             %{
               "windGustTime" => 1_570_082_400,
               "pressure" => 1010.16,
               "apparentTemperatureLowTime" => 1_570_165_200,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_570_111_200,
               "ozone" => 266.1,
               "dewPoint" => 22.28,
               "temperatureLowTime" => 1_570_165_200,
               "precipIntensityMax" => 0.226,
               "apparentTemperatureMaxTime" => 1_570_111_200,
               "apparentTemperatureMax" => 35.29,
               "apparentTemperatureHigh" => 35.29,
               "apparentTemperatureMin" => 22.25,
               "icon" => "rain",
               "temperatureLow" => 22.12,
               "uvIndexTime" => 1_570_100_400,
               "precipIntensity" => 0.0521,
               "visibility" => 16.093,
               "temperatureMin" => 21.45,
               "apparentTemperatureMinTime" => 1_570_078_800,
               "temperatureMinTime" => 1_570_078_800,
               "temperatureHighTime" => 1_570_111_200,
               "precipProbability" => 0.43,
               "temperatureHigh" => 31.19,
               "time" => 1_570_057_200,
               "windGust" => 7.8,
               "windSpeed" => 3.34,
               "apparentTemperatureHighTime" => 1_570_111_200,
               "cloudCover" => 0.91,
               "windBearing" => 181,
               "temperatureMax" => 31.19,
               "sunriseTime" => 1_570_079_157,
               "precipIntensityMaxTime" => 1_570_082_400,
               "moonPhase" => 0.19,
               "sunsetTime" => 1_570_122_397,
               "summary" => "Humid and overcast throughout the day.",
               "uvIndex" => 6,
               "apparentTemperatureLow" => 22.97,
               "humidity" => 0.82
             },
             %{
               "windGustTime" => 1_570_161_600,
               "pressure" => 1009.44,
               "apparentTemperatureLowTime" => 1_570_251_600,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_570_197_600,
               "ozone" => 264.4,
               "dewPoint" => 22.72,
               "temperatureLowTime" => 1_570_251_600,
               "precipIntensityMax" => 0.2488,
               "apparentTemperatureMaxTime" => 1_570_197_600,
               "apparentTemperatureMax" => 36.31,
               "apparentTemperatureHigh" => 36.31,
               "apparentTemperatureMin" => 22.97,
               "icon" => "partly-cloudy-day",
               "temperatureLow" => 22.75,
               "uvIndexTime" => 1_570_186_800,
               "precipIntensity" => 0.0373,
               "visibility" => 16.093,
               "temperatureMin" => 22.12,
               "apparentTemperatureMinTime" => 1_570_165_200,
               "temperatureMinTime" => 1_570_165_200,
               "temperatureHighTime" => 1_570_197_600,
               "precipProbability" => 0.19,
               "temperatureHigh" => 31.89,
               "time" => 1_570_143_600,
               "windGust" => 9.45,
               "windSpeed" => 3.82,
               "apparentTemperatureHighTime" => 1_570_197_600,
               "cloudCover" => 0.74,
               "windBearing" => 200,
               "temperatureMax" => 31.89,
               "sunriseTime" => 1_570_165_556,
               "precipIntensityMaxTime" => 1_570_212_000,
               "moonPhase" => 0.22,
               "sunsetTime" => 1_570_208_760,
               "summary" => "Humid and mostly cloudy throughout the day.",
               "uvIndex" => 8,
               "apparentTemperatureLow" => 23.69,
               "humidity" => 0.81
             },
             %{
               "windGustTime" => 1_570_251_600,
               "pressure" => 1009.8,
               "apparentTemperatureLowTime" => 1_570_338_000,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_570_276_800,
               "ozone" => 262.2,
               "dewPoint" => 22.92,
               "temperatureLowTime" => 1_570_338_000,
               "precipIntensityMax" => 4.3474,
               "apparentTemperatureMaxTime" => 1_570_276_800,
               "apparentTemperatureMax" => 32.94,
               "apparentTemperatureHigh" => 32.94,
               "apparentTemperatureMin" => 23.69,
               "icon" => "rain",
               "temperatureLow" => 20.81,
               "uvIndexTime" => 1_570_273_200,
               "precipIntensity" => 0.5879,
               "visibility" => 15.611,
               "temperatureMin" => 22.75,
               "apparentTemperatureMinTime" => 1_570_251_600,
               "temperatureMinTime" => 1_570_251_600,
               "temperatureHighTime" => 1_570_276_800,
               "precipProbability" => 0.79,
               "temperatureHigh" => 29.11,
               "time" => 1_570_230_000,
               "windGust" => 9.39,
               "windSpeed" => 3.62,
               "apparentTemperatureHighTime" => 1_570_276_800,
               "cloudCover" => 0.73,
               "windBearing" => 216,
               "temperatureMax" => 29.11,
               "sunriseTime" => 1_570_251_955,
               "precipIntensityMaxTime" => 1_570_287_600,
               "moonPhase" => 0.25,
               "sunsetTime" => 1_570_295_123,
               "summary" => "Rain and humid throughout the day.",
               "uvIndex" => 7,
               "apparentTemperatureLow" => 21.56
             },
             %{
               "windGustTime" => 1_570_395_600,
               "pressure" => 1010.26,
               "apparentTemperatureLowTime" => 1_570_413_600,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_570_370_400,
               "ozone" => 261.2,
               "dewPoint" => 23.34,
               "temperatureLowTime" => 1_570_413_600,
               "precipIntensityMax" => 0.6534,
               "apparentTemperatureMaxTime" => 1_570_370_400,
               "apparentTemperatureMax" => 34.55,
               "apparentTemperatureHigh" => 34.55,
               "apparentTemperatureMin" => 21.56,
               "icon" => "rain",
               "temperatureLow" => 21.12,
               "uvIndexTime" => 1_570_363_200,
               "precipIntensity" => 0.2187,
               "visibility" => 14.983,
               "temperatureMin" => 20.81,
               "apparentTemperatureMinTime" => 1_570_338_000,
               "temperatureMinTime" => 1_570_338_000,
               "temperatureHighTime" => 1_570_370_400,
               "precipProbability" => 0.95,
               "temperatureHigh" => 28.77,
               "time" => 1_570_316_400,
               "windGust" => 9.24,
               "windSpeed" => 2.54,
               "apparentTemperatureHighTime" => 1_570_370_400,
               "cloudCover" => 0.84,
               "windBearing" => 208,
               "temperatureMax" => 28.77,
               "sunriseTime" => 1_570_338_354,
               "precipIntensityMaxTime" => 1_570_323_600,
               "moonPhase" => 0.29,
               "sunsetTime" => 1_570_381_486,
               "summary" => "Light rain until evening.",
               "uvIndex" => 6
             },
             %{
               "windGustTime" => 1_570_489_200,
               "pressure" => 1009.67,
               "apparentTemperatureLowTime" => 1_570_507_200,
               "precipType" => "rain",
               "temperatureMaxTime" => 1_570_453_200,
               "ozone" => 260.4,
               "dewPoint" => 23.33,
               "temperatureLowTime" => 1_570_507_200,
               "precipIntensityMax" => 0.8178,
               "apparentTemperatureMaxTime" => 1_570_453_200,
               "apparentTemperatureMax" => 36.11,
               "apparentTemperatureHigh" => 36.11,
               "apparentTemperatureMin" => 21.9,
               "icon" => "partly-cloudy-day",
               "temperatureLow" => 22.31,
               "uvIndexTime" => 1_570_446_000,
               "precipIntensity" => 0.0851,
               "visibility" => 16.093,
               "temperatureMin" => 21.12,
               "apparentTemperatureMinTime" => 1_570_413_600,
               "temperatureMinTime" => 1_570_413_600,
               "temperatureHighTime" => 1_570_453_200,
               "precipProbability" => 0.21,
               "temperatureHigh" => 30.76,
               "time" => 1_570_402_800,
               "windGust" => 7.34,
               "windSpeed" => 1.93,
               "apparentTemperatureHighTime" => 1_570_453_200,
               "cloudCover" => 0.5,
               "windBearing" => 192,
               "temperatureMax" => 30.76,
               "sunriseTime" => 1_570_424_754,
               "precipIntensityMaxTime" => 1_570_449_600,
               "moonPhase" => 0.32,
               "sunsetTime" => 1_570_467_850,
               "summary" => "Possible light rain in the morning."
             }
           ],
           "icon" => "rain",
           "summary" =>
             "Rain today through Sunday, with high temperatures falling to 29°C on Sunday."
         },
         "flags" => %{
           "sources" => ["cmc", "gfs", "icon", "isd", "madis"],
           "units" => "si"
         },
         "hourly" => %{
           "data" => [
             %{
               "apparentTemperature" => 33.45,
               "cloudCover" => 0.57,
               "dewPoint" => 21.32,
               "humidity" => 0.58,
               "icon" => "partly-cloudy-day",
               "ozone" => 259.6,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1007.74,
               "summary" => "Mostly Cloudy",
               "temperature" => 30.55,
               "time" => 1_569_852_000,
               "uvIndex" => 5,
               "visibility" => 16.093,
               "windBearing" => 128,
               "windGust" => 3.98,
               "windSpeed" => 2.92
             },
             %{
               "apparentTemperature" => 33.16,
               "cloudCover" => 0.38,
               "dewPoint" => 21.07,
               "humidity" => 0.57,
               "icon" => "partly-cloudy-day",
               "ozone" => 258.7,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1007.13,
               "summary" => "Partly Cloudy",
               "temperature" => 30.47,
               "time" => 1_569_855_600,
               "uvIndex" => 3,
               "visibility" => 16.093,
               "windBearing" => 135,
               "windGust" => 3.82,
               "windSpeed" => 2.86
             },
             %{
               "apparentTemperature" => 32.52,
               "cloudCover" => 0.27,
               "dewPoint" => 21.11,
               "humidity" => 0.59,
               "icon" => "partly-cloudy-day",
               "ozone" => 258.7,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1007.55,
               "summary" => "Partly Cloudy",
               "temperature" => 29.91,
               "time" => 1_569_859_200,
               "uvIndex" => 1,
               "visibility" => 16.093,
               "windBearing" => 152,
               "windGust" => 3.49,
               "windSpeed" => 2.43
             },
             %{
               "apparentTemperature" => 30.96,
               "cloudCover" => 0.21,
               "dewPoint" => 21.33,
               "humidity" => 0.65,
               "icon" => "partly-cloudy-day",
               "ozone" => 259.4,
               "precipIntensity" => 0.0234,
               "precipProbability" => 0.04,
               "precipType" => "rain",
               "pressure" => 1007.91,
               "summary" => "Partly Cloudy",
               "temperature" => 28.52,
               "time" => 1_569_862_800,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 173,
               "windGust" => 3.12,
               "windSpeed" => 1.83
             },
             %{
               "apparentTemperature" => 29.27,
               "cloudCover" => 0.19,
               "dewPoint" => 21.48,
               "humidity" => 0.71,
               "icon" => "partly-cloudy-night",
               "ozone" => 260.2,
               "precipIntensity" => 0.0432,
               "precipProbability" => 0.05,
               "precipType" => "rain",
               "pressure" => 1008.51,
               "summary" => "Partly Cloudy",
               "temperature" => 27.19,
               "time" => 1_569_866_400,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 188,
               "windGust" => 3.35,
               "windSpeed" => 1.53
             },
             %{
               "apparentTemperature" => 28.11,
               "cloudCover" => 0.23,
               "dewPoint" => 21.54,
               "humidity" => 0.75,
               "icon" => "partly-cloudy-night",
               "ozone" => 261.3,
               "precipIntensity" => 0.039,
               "precipProbability" => 0.04,
               "precipType" => "rain",
               "pressure" => 1009.29,
               "summary" => "Partly Cloudy",
               "temperature" => 26.37,
               "time" => 1_569_870_000,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 195,
               "windGust" => 4.73,
               "windSpeed" => 1.83
             },
             %{
               "apparentTemperature" => 26.52,
               "cloudCover" => 0.31,
               "dewPoint" => 21.56,
               "humidity" => 0.77,
               "icon" => "partly-cloudy-night",
               "ozone" => 262.6,
               "precipIntensity" => 0.0246,
               "precipProbability" => 0.04,
               "precipType" => "rain",
               "pressure" => 1010.27,
               "summary" => "Partly Cloudy",
               "temperature" => 25.86,
               "time" => 1_569_873_600,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 198,
               "windGust" => 6.69,
               "windSpeed" => 2.53
             },
             %{
               "apparentTemperature" => 26.22,
               "cloudCover" => 0.36,
               "dewPoint" => 21.48,
               "humidity" => 0.78,
               "icon" => "partly-cloudy-night",
               "ozone" => 263.7,
               "precipIntensity" => 0.0234,
               "precipProbability" => 0.04,
               "precipType" => "rain",
               "pressure" => 1010.86,
               "summary" => "Partly Cloudy",
               "temperature" => 25.57,
               "time" => 1_569_877_200,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 201,
               "windGust" => 8.1,
               "windSpeed" => 3.09
             },
             %{
               "apparentTemperature" => 26,
               "cloudCover" => 0.3,
               "dewPoint" => 21.44,
               "humidity" => 0.79,
               "icon" => "partly-cloudy-night",
               "ozone" => 264.4,
               "precipIntensity" => 0.0519,
               "precipProbability" => 0.09,
               "precipType" => "rain",
               "pressure" => 1011.05,
               "summary" => "Partly Cloudy",
               "temperature" => 25.35,
               "time" => 1_569_880_800,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 205,
               "windGust" => 8.4,
               "windSpeed" => 3.11
             },
             %{
               "apparentTemperature" => 25.69,
               "cloudCover" => 0.21,
               "dewPoint" => 21.36,
               "humidity" => 0.8,
               "icon" => "partly-cloudy-night",
               "ozone" => 264.9,
               "precipIntensity" => 0.1143,
               "precipProbability" => 0.17,
               "precipType" => "rain",
               "pressure" => 1010.95,
               "summary" => "Partly Cloudy",
               "temperature" => 25.04,
               "time" => 1_569_884_400,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 211,
               "windGust" => 8.16,
               "windSpeed" => 2.87
             },
             %{
               "apparentTemperature" => 25.29,
               "cloudCover" => 0.21,
               "dewPoint" => 21.28,
               "humidity" => 0.82,
               "icon" => "partly-cloudy-night",
               "ozone" => 264.9,
               "precipIntensity" => 0.1545,
               "precipProbability" => 0.18,
               "precipType" => "rain",
               "pressure" => 1010.73,
               "summary" => "Partly Cloudy",
               "temperature" => 24.64,
               "time" => 1_569_888_000,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 214,
               "windGust" => 7.91,
               "windSpeed" => 2.75
             },
             %{
               "apparentTemperature" => 24.83,
               "cloudCover" => 0.39,
               "dewPoint" => 21.43,
               "humidity" => 0.85,
               "icon" => "partly-cloudy-night",
               "ozone" => 264.4,
               "precipIntensity" => 0.1162,
               "precipProbability" => 0.18,
               "precipType" => "rain",
               "pressure" => 1010.43,
               "summary" => "Partly Cloudy",
               "temperature" => 24.15,
               "time" => 1_569_891_600,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 214,
               "windGust" => 7.83,
               "windSpeed" => 2.93
             },
             %{
               "apparentTemperature" => 24.55,
               "cloudCover" => 0.67,
               "dewPoint" => 21.63,
               "humidity" => 0.88,
               "icon" => "partly-cloudy-night",
               "ozone" => 263.3,
               "precipIntensity" => 0.0548,
               "precipProbability" => 0.15,
               "precipType" => "rain",
               "pressure" => 1010.01,
               "summary" => "Mostly Cloudy",
               "temperature" => 23.83,
               "time" => 1_569_895_200,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 211,
               "windGust" => 7.75,
               "windSpeed" => 3.21
             },
             %{
               "apparentTemperature" => 24.39,
               "cloudCover" => 0.87,
               "dewPoint" => 21.63,
               "humidity" => 0.88,
               "icon" => "partly-cloudy-night",
               "ozone" => 262.7,
               "precipIntensity" => 0.0222,
               "precipProbability" => 0.12,
               "precipType" => "rain",
               "pressure" => 1009.88,
               "summary" => "Mostly Cloudy",
               "temperature" => 23.66,
               "time" => 1_569_898_800,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 208,
               "windGust" => 7.81,
               "windSpeed" => 3.45
             },
             %{
               "apparentTemperature" => 24.19,
               "cloudCover" => 0.94,
               "dewPoint" => 21.62,
               "humidity" => 0.89,
               "icon" => "cloudy",
               "ozone" => 262.1,
               "precipIntensity" => 0.0139,
               "precipProbability" => 0.1,
               "precipType" => "rain",
               "pressure" => 1010.22,
               "summary" => "Overcast",
               "temperature" => 23.45,
               "time" => 1_569_902_400,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 207,
               "windGust" => 8.25,
               "windSpeed" => 3.54
             },
             %{
               "apparentTemperature" => 23.54,
               "cloudCover" => 0.95,
               "dewPoint" => 21.8,
               "humidity" => 0.94,
               "icon" => "cloudy",
               "ozone" => 261.7,
               "precipIntensity" => 0.0116,
               "precipProbability" => 0.08,
               "precipType" => "rain",
               "pressure" => 1010.83,
               "summary" => "Overcast",
               "temperature" => 22.74,
               "time" => 1_569_906_000,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 205,
               "windGust" => 8.83,
               "windSpeed" => 3.57
             },
             %{
               "apparentTemperature" => 23.72,
               "cloudCover" => 0.93,
               "dewPoint" => 22.28,
               "humidity" => 0.97,
               "icon" => "cloudy",
               "ozone" => 261.6,
               "precipIntensity" => 0.0083,
               "precipProbability" => 0.06,
               "precipType" => "rain",
               "pressure" => 1011.42,
               "summary" => "Humid and Overcast",
               "temperature" => 22.86,
               "time" => 1_569_909_600,
               "uvIndex" => 0,
               "visibility" => 16.093,
               "windBearing" => 204,
               "windGust" => 9.01,
               "windSpeed" => 3.71
             },
             %{
               "apparentTemperature" => 25.01,
               "cloudCover" => 0.87,
               "dewPoint" => 22.96,
               "humidity" => 0.93,
               "icon" => "partly-cloudy-day",
               "ozone" => 262.2,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1011.98,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 24.11,
               "time" => 1_569_913_200,
               "uvIndex" => 2,
               "visibility" => 16.093,
               "windBearing" => 208,
               "windGust" => 8.44,
               "windSpeed" => 4.08
             },
             %{
               "apparentTemperature" => 28,
               "cloudCover" => 0.79,
               "dewPoint" => 23.55,
               "humidity" => 0.86,
               "icon" => "partly-cloudy-day",
               "ozone" => 263.2,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1012.05,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 26.04,
               "time" => 1_569_916_800,
               "uvIndex" => 4,
               "visibility" => 16.093,
               "windBearing" => 214,
               "windGust" => 7.47,
               "windSpeed" => 4.55
             },
             %{
               "apparentTemperature" => 31.05,
               "cloudCover" => 0.73,
               "dewPoint" => 23.8,
               "humidity" => 0.8,
               "icon" => "partly-cloudy-day",
               "ozone" => 263.8,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1011.68,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 27.57,
               "time" => 1_569_920_400,
               "uvIndex" => 6,
               "visibility" => 16.093,
               "windBearing" => 219,
               "windGust" => 6.52,
               "windSpeed" => 4.79
             },
             %{
               "apparentTemperature" => 33.07,
               "cloudCover" => 0.73,
               "dewPoint" => 23.62,
               "humidity" => 0.73,
               "icon" => "partly-cloudy-day",
               "ozone" => 263.8,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1011.3,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 28.88,
               "time" => 1_569_924_000,
               "uvIndex" => 7,
               "visibility" => 16.093,
               "windBearing" => 220,
               "windGust" => 5.77,
               "windSpeed" => 4.59
             },
             %{
               "apparentTemperature" => 34.29,
               "cloudCover" => 0.76,
               "dewPoint" => 23.21,
               "humidity" => 0.67,
               "icon" => "partly-cloudy-day",
               "ozone" => 263.6,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1010.63,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 29.96,
               "time" => 1_569_927_600,
               "uvIndex" => 7,
               "visibility" => 16.093,
               "windBearing" => 219,
               "windGust" => 5.04,
               "windSpeed" => 4.14
             },
             %{
               "apparentTemperature" => 35.4,
               "cloudCover" => 0.76,
               "dewPoint" => 22.86,
               "humidity" => 0.62,
               "icon" => "partly-cloudy-day",
               "ozone" => 263.2,
               "precipIntensity" => 0.0062,
               "precipProbability" => 0.02,
               "precipType" => "rain",
               "pressure" => 1009.7,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 31.04,
               "time" => 1_569_931_200,
               "uvIndex" => 7,
               "visibility" => 16.093,
               "windBearing" => 222,
               "windGust" => 4.35,
               "windSpeed" => 3.74
             },
             %{
               "apparentTemperature" => 36.2,
               "cloudCover" => 0.72,
               "dewPoint" => 22.73,
               "humidity" => 0.59,
               "icon" => "partly-cloudy-day",
               "ozone" => 262.8,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1008.77,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 31.76,
               "time" => 1_569_934_800,
               "uvIndex" => 6,
               "visibility" => 16.093,
               "windBearing" => 229,
               "windGust" => 3.52,
               "windSpeed" => 3.5
             },
             %{
               "apparentTemperature" => 36.54,
               "cloudCover" => 0.65,
               "dewPoint" => 22.62,
               "humidity" => 0.57,
               "icon" => "partly-cloudy-day",
               "ozone" => 262.3,
               "precipIntensity" => 0,
               "precipProbability" => 0,
               "pressure" => 1007.67,
               "summary" => "Humid and Mostly Cloudy",
               "temperature" => 32.11,
               "time" => 1_569_938_400,
               "uvIndex" => 5,
               "visibility" => 16.093,
               "windBearing" => 241,
               "windGust" => 3.3,
               "windSpeed" => 3.3
             }
           ],
           "icon" => "partly-cloudy-day",
           "summary" => "Humid and mostly cloudy throughout the day."
         },
         "latitude" => 11,
         "longitude" => 11,
         "offset" => 1,
         "timezone" => "Africa/Lagos"
       },
       headers: [
         {"Date", "Mon, 30 Sep 2019 14:57:46 GMT"},
         {"Content-Type", "application/json; charset=utf-8"},
         {"Content-Length", "25675"},
         {"Connection", "keep-alive"},
         {"X-Authentication-Time", "810ms"},
         {"X-Forecast-API-Calls", "4"},
         {"Cache-Control", "max-age=600"},
         {"Expires", "Mon, 30 Sep 2019 15:07:46 +0000"},
         {"X-Response-Time", "37.964ms"},
         {"Vary", "Accept-Encoding"}
       ],
       request: %HTTPoison.Request{
         body: "",
         headers: [],
         method: :get,
         options: [],
         params: %{},
         url: "https://api.darksky.net/forecast/"
       },
       request_url: "https://api.darksky.net/forecast/",
       status_code: 200
     }}
  end
end
